tab-complete:
  enabled: true
  bypass-permission: "mythiccore.bypass.tabcomplete"
  # mode:
  #   blacklist: allow by default, block when input starts with any prefix in blacklist
  #   whitelist: block by default, allow only when input starts with any prefix in whitelist
  mode: "blacklist"
  # Prefix list, case-insensitive. Entries without leading '/' will be normalized to start with '/'.
  # Example (blacklist):
  #   mode: "blacklist"
  #   blacklist:
  #     - "/pl"
  #     - "/plugins"
  #     - "/bukkit:"
  blacklist: [ ]
  #
  # Example (whitelist):
  #   mode: "whitelist"
  #   whitelist:
  #     - "/msg"
  #     - "/tell"
  #     - "/r"
  whitelist: [ ]

plugins-command:
  enabled: true
  bypass-permission: "mythiccore.bypass.pluginslist"
  commands:
    - "pl"
    - "plugins"
    - "bukkit:pl"
    - "bukkit:plugins"

  # Key: real plugin name (plugin.getDescription().getName())
  # Value:
  #   "" or "-" => hide this plugin from /pl list
  #   otherwise => replace displayed plugin name (supports & color codes)
  # Example:
  #   replacements:
  #     "Matrix": "Vulcan"
  #     "GrimAC": "-"     # hide
  replacements: { }
  # Supports: %count%
  prefix: "&fPlugins (%count%): "
