tab-complete:
  enabled: true
  bypass-permission: "mythiccore.bypass.tab-complete"
  # blacklist: 默认放行, 命中前缀时拦截。
  # whitelist: 默认拦截, 只有命中前缀时放行。
  mode: "blacklist"
  blacklist-prefixes: [ ]
  whitelist-prefixes: [ ]

fake-anti-cheat:
  enabled: false

plugins-command:
  enabled: true
  bypass-permission: "mythiccore.bypass.plugins-command"
  aliases:
    - "pl"
    - "plugins"
    - "bukkit:pl"
    - "bukkit:plugins"
  # Key: 插件真实名称。
  # Value:
  #   "-" 或空串表示隐藏。
  #   其他值表示替换显示名, 支持 & 颜色代码。
  replacements: { }
