name: MythicCore
version: '${version}'
main: cn.mythiclnd.mythiccore.PluginMain
load: STARTUP
depend: [ProtocolLib]

commands:
  mythiccore:
    description: MythicCore main command
    aliases: [mcr]
    usage: "/<command> [reload]"

permissions:
  mythiccore.bypass.tab-complete:
    description: Allows using command tab completion even when MythicCore blocks it
    default: op
  mythiccore.bypass.plugins-command:
    description: Allows using the original /pl output (MythicCore will not override)
    default: op
  mythiccore.command.reload:
    description: Allows reloading MythicCore configuration
    default: op
